apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: nids-producer
          imagePullPolicy: Never
          env:
            - name: KAFKA_SERVER
              value: "kafka:9092"
            - name: PARQUET_PATH
              value: "/app/cicids_sample.parquet"
            - name: SAMPLE_SIZE
              value: "2000"
