FROM python:3.11-slim

WORKDIR /app

COPY requirements-consumer.txt .

RUN pip install --no-cache-dir -r requirements-consumer.txt

COPY rf_model.pkl .

COPY consumer.py .

CMD ["python", "consumer.py"]
